const labels_en = {
    "fco_title": "FULL CORPORATE OFFER FOR",
    "date": "Date",
    "reference": "Reference",
    "to": "To",
    "company_name": "Company Name",
    "address": "Address",
    "website": "Website",
    "email": "Email",
    "phone": "Phone Number",
    "dear_sir": "Dear Sir,",
    "intro_p1": "We, {seller_company}, hereby formally confirm our intent and capability to supply {product_name}. We affirm that our company is fully prepared, willing, and able to sell the product strictly in accordance with the specifications, quantities, pricing, and commercial terms outlined in this Full Corporate Offer (FCO). This declaration is issued with full corporate authority and complete responsibility on behalf of our company.",
    "trial_shipment_title": "QUANTITY \\& PRICING FOR TRIAL SHIPMENT",
    "trial_container": "Trial Container",
    "price": "Price",
    "trial_shipment_value": "Trial Shipment Value",
    "trial_quantity_mt": "Trial Quantity in MT",
    "loading_capacity": "Loading Capacity",
    "loading_port": "Loading Port",
    "destination_port": "Destination Port",
    "delivery_time": "Delivery Time",
    "contract_shipment_title": "QUANTITY \\& PRICING FOR YEARLY CONTRACT SHIPMENT",
    "quantity": "Quantity",
    "monthly_shipment_value": "Monthly Shipment Value",
    "annual_contract_value": "Annual Contract Value",
    "contract_duration": "Contract Duration",
    "annual_contract_quantity": "Annual Contract Quantity",
    "product_specification": "PRODUCT SPECIFICATION",
    "category": "CATEGORY",
    "specification": "SPECIFICATION",
    "product_name_label": "Product Name",
    "grade": "Grade",
    "origin": "Origin",
    "origin_cert": "Origin / Certification",
    "processing": "Processing",
    "appearance": "Appearance",
    "odor": "Odor",
    "bones": "Bones",
    "blood_stains": "Blood / Blood Stains",
    "moisture_content": "Moisture Content",
    "damage": "Damage",
    "chicken_paw_pad": "Chicken Paw Pad",
    "weight_per_piece": "Weight per Piece",
    "length_per_piece": "Length per Piece",
    "packaging": "Packaging",
    "inner_packing": "Inner Packing",
    "carton_weight": "Carton Weight",
    "freezing_temp": "Freezing Temperature",
    "storage_temp": "Storage Temperature",
    "transport_temp": "Transportation Temperature",
    "freezing_process": "Freezing Process",
    "shelf_life": "Shelf Life",
    "packaging_note": "Packaging Note",
    "product_discharge": "PRODUCT DISCHARGE",
    "discharge_p1": "The shipment shall begin within 15-20 days after receipt and confirmation of the payment instrument in seller's Bank, after the contract is signed.",
    "discharge_p2": "The Date of bill of Lading shall be considered the date of delivery.",
    "discharge_p3": "Seller is responsible for all supervision, fees and/ or levies at the port of loading.",
    "discharge_p4": "Not later than 72 hours from the completion of loading, the seller's agent shall email the buyer and inform the vessel's sailing date and the expected time of arrival at the port of destination.",
    "discharge_p5": "All port of loading charges are for the account of the seller and all port of discharge charges are for the account of the buyer.",
    "commercial_terms": "COMMERCIAL TERMS",
    "commercial_note": "(This is our basis payment terms but still it should be editable)",
    "trial_shipment": "TRIAL SHIPMENT",
    "trial_payment_text": "The Buyer will provide irrevocable, operative, and transferable DLC (MT700) for trial containers. The Buyer shall make 100\\% payment at the loading port against presentation of shipping documents via TT (MT 103). The Seller shall ship the goods as per the agreed Proforma Invoice and, upon completion of loading at the port of shipment, present copies of the shipping documents, including but not limited to the Bill of Lading, Commercial Invoice, Packing List, Health Certificate, and other required export documents, to the Buyer. Full payment shall be remitted by the Buyer immediately upon confirmation of loading and presentation of documents. Release of the original shipping documents shall be made only after receipt of 100\\% payment through normal banking channels via TT (MT103).",
    "monthly_shipment": "MONTHLY SHIPMENT",
    "monthly_payment_text": "Buyer will open an irrevocable, operative, and transferable DLC (MT700) for the value of one month shipment quantity against the proforma invoice \\& SPA, issued and confirmed by world top 100 Banks valid for 365 + 1 days (or 180 days x 2 subject to the issuing bank's rule). Upon completion of loading and issuance of the Bill of Lading, the Seller shall provide copies of the commercial invoice, Bill of Lading, Packing List, and other relevant shipping documents to the Buyer. The Buyer shall remit 100\\% payment immediately upon confirmation of the above mentioned shipping documents. Payment shall be effected via MT103 / TT bank-to-bank SWIFT transfer. Release of the original Bill of Lading and full set of original shipping documents shall be made only after confirmation of full payment through normal banking channels.",
    "payment_tt": "PAYMENT VIA TELEGRAPHIC TRANSFER (TT/MT103)",
    "payment_tt_text": "The Buyer shall effect payment for shipments by way of Telegraphic Transfer (TT/MT103) upon receipt of confirmation from the Seller's nominated bank via SWIFT that the original shipping documents have been duly submitted and are held in custody by the bank. The Seller shall, prior to such confirmation, provide the Buyer with scanned/digital copies of all relevant shipping documents for advance review and verification. The Buyer will still be providing DLC MT700 as a security financial instrument for contract shipment.",
    "dlc": "DOCUMENTARY LETTER OF CREDIT (DLC/MT700)",
    "dlc_text": "The DLC (MT700) shall serve as a supporting financial instrument for the purpose of providing transactional assurance and security to both parties. For the avoidance of doubt, the DLC shall not constitute the primary mode of payment. Actual settlement for each shipment shall be effected exclusively via TT/MT103.",
    "telex": "TELEX RELEASE",
    "telex_text": "The Seller shall arrange telex release of the cargo upon receipt of full payment, unless otherwise mutually agreed.",
    "product_doc": "PRODUCT DOCUMENTATION",
    "doc_intro": "A full set of the following documents which will be legitimate for shipment from Brazil will be presented.",
    "doc_1": "Full set of clean on -- board marine bill of lading made out to order and blank endorsed, 1/3 clearly marked `Freight Prepaid'' in 1 original",
    "doc_2": "Commercial Invoice issued by the seller indicating the contract number, DLC/SBLC number, Description of the goods, gross / net weights of the goods in 1 Original.",
    "doc_3": "Packaging list 1 originals showing contract no., seal no., container no., gross / net weight, B/L no., date. Quantity loaded and loading port.",
    "doc_4": "Certificate of origin issued by the relevant authority of the country of origin of Brazil in 1 original",
    "doc_5": "Certificate of Quality and quantity issued by CCIC Brazil, 1 original",
    "doc_6": "Veterinary health certificate issued by veterinary office for the record of China entry- Exit inspection and quarantine in 1 originals",
    "doc_7": "Insurance policy/ certificate in 1 original for 110\\% of the invoice value, covering ocean marine transportation all risk.",
    "doc_8": "Commodity bilingual English- Chinese label samples in 1 original.",
    "doc_9": "Slaughterhouse SIF certificate in 1 copy",
    "doc_10": "Export / shipper certificate of GACC Registration in 1 Copy",
    "doc_11": "HALAL certificate in 1 original",
    "procedures": "PROCEDURES",
    "proc_note": "(This is our basis procedure but still it should be editable)",
    "proc_1": "The Buyer issues the LOI (Letter of Intent) to the Seller.",
    "proc_2": "The Seller issues the FCO (Full Corporate Offer) to the Buyer.",
    "proc_3": "Upon acceptance, the Buyer signs, seals, and returns the FCO.",
    "proc_4": "The Buyer issues the ICPO (Irrevocable Corporate Purchase Order).",
    "proc_5": "The Seller issues the SPA (Sales and Purchase Agreement).",
    "proc_6": "The Buyer provides POF (Proof of Funds) by BCL (Bank Comfort Letter).",
    "proc_7": "Upon signing and sealing of the SPA, the Seller issues the Proforma Invoice (PI).",
    "proc_8": "The Buyer's bank issues an irrevocable, operative, and transferable DLC (MT700), covering the agreed shipment quantity in accordance with the SPA and payment terms. The DLC shall be issued and confirmed by a Top 100 World Bank and remain valid as per agreed contract terms.",
    "proc_9": "The Seller arranges inspection for quality and quantity through CCIC Brazil at the Seller's expense, completes loading, and prepares the shipping documents.",
    "proc_10": "Upon completion of loading and issuance of the Bill of Lading, the Seller provides copies of shipping documents to the Buyer, including but not limited to the Bill of Lading, Commercial Invoice, Packing List, Health Certificate, and other relevant export documents.",
    "proc_11": "The Buyer remits 100\\% payment immediately upon confirmation of loading and presentation of shipping documents via TT / MT103 bank-to-bank SWIFT transfer.",
    "proc_12": "Release of the original Bill of Lading and full set of original shipping documents shall be made only after confirmation of 100\\% payment through normal banking channels.",
    "proc_13": "The Seller permits the Buyer or the Buyer's appointed representative to witness the loading process at the loading warehouse, at the Buyer's expense.",
    "proc_14": "The Buyer shall be responsible for customs clearance, unloading at destination, and any penalties arising from delayed unloading. The Buyer shall notify the Seller in writing of the appointed clearing agent details at the time of payment confirmation.",
    "seller_details": "SELLER DETAILS",
    "seller_bank": "SELLER BANKING DETAILS",
    "contact_person": "Contact Person",
    "whatsapp": "WhatsApp",
    "bank_name": "Bank Name",
    "bank_address": "Bank Address",
    "account_name": "Account Name",
    "account_number": "Account Number",
    "swift_code": "Swift Code",
    "buyer_company_info": "BUYER COMPANY INFORMATION",
    "country": "Country",
    "phone_no": "Phone No.",
    "buyer_bank_info": "BUYER BANK INFORMATION",
    "bank_swift_code": "Bank Swift Code",
    "bank_officer": "Bank Officer/Email",
    "bank_charges_note": "Bank Charges: All banking Charges from Buyer's Bank shall be borne by the buyer, and all banking charges incurred at Seller's Financier's Bank will be borne by the Seller Financier's.",
    "note_1": "Note: No contact with the Seller's or Buyer's bank(s) shall be made without the explicit written permission of the Seller or Buyer. In the event that an alternate bank account is to be used, the Seller and Buyer shall notify each other in writing of the new bank coordinates. Both parties are required to inform each other in advance before forwarding any financial instructions or correspondence to the bank.",
    "note_2": "Please Note: A final SPA will be signed between end seller and the buyer once this FCO is accepted, signed and sealed by the buyer.",
    "validity_offer": "VALIDITY OF OFFER",
    "validity_text": "This FCO remains valid until its expiry date",
    "auth_sig": "AUTHORIZED SIGNATURES",
    "seller_sig": "FOR AND ON BEHALF OF SELLER",
    "buyer_sig": "FOR AND ON BEHALF OF BUYER",
};

const labels_zh = {
    "fco_title": "FULL CORPORATE OFFER FOR / 完整企业报价",
    "date": "Date / 日期",
    "reference": "Reference / 编号",
    "to": "To / 致",
    "company_name": "Company Name / 公司名称",
    "address": "Address / 地址",
    "website": "Website / 网站",
    "email": "Email / 邮箱",
    "phone": "Phone Number / 电话号码",
    "dear_sir": "Dear Sir, / 尊敬的先生，",
    "intro_p1": "We, {seller_company}, hereby formally confirm our intent and capability to supply {product_name}. We affirm that our company is fully prepared, willing, and able to sell the product strictly in accordance with the specifications, quantities, pricing, and commercial terms outlined in this Full Corporate Offer (FCO). This declaration is issued with full corporate authority and complete responsibility on behalf of our company. / 我们，{seller_company}，特此正式确认我们供应 {product_name} 的意向和能力。我们确认，我们公司已完全准备好、愿意且能够严格按照本完整企业报价 (FCO) 中列出的规格、数量、定价和商业条款销售产品。本声明代表我们公司以完全的企业授权和完全的责任发布。",
    "trial_shipment_title": "QUANTITY \\& PRICING FOR TRIAL SHIPMENT / 试运数量与价格",
    "trial_container": "Trial Container / 试运集装箱",
    "price": "Price / 价格",
    "trial_shipment_value": "Trial Shipment Value / 试运价值",
    "trial_quantity_mt": "Trial Quantity in MT / 试运数量 (公吨)",
    "loading_capacity": "Loading Capacity / 装载能力",
    "loading_port": "Loading Port / 装货港",
    "destination_port": "Destination Port / 目的港",
    "delivery_time": "Delivery Time / 交货时间",
    "contract_shipment_title": "QUANTITY \\& PRICING FOR YEARLY CONTRACT SHIPMENT / 年度合同数量与价格",
    "quantity": "Quantity / 数量",
    "monthly_shipment_value": "Monthly Shipment Value / 月度发货价值",
    "annual_contract_value": "Annual Contract Value / 年度合同价值",
    "contract_duration": "Contract Duration / 合同期限",
    "annual_contract_quantity": "Annual Contract Quantity / 年度合同数量",
    "product_specification": "PRODUCT SPECIFICATION / 产品规格",
    "category": "CATEGORY / 类别",
    "specification": "SPECIFICATION / 规格",
    "product_name_label": "Product Name / 产品名称",
    "grade": "Grade / 等级",
    "origin": "Origin / 产地",
    "origin_cert": "Origin / Certification / 产地/认证",
    "processing": "Processing / 加工方式",
    "appearance": "Appearance / 外观",
    "odor": "Odor / 气味",
    "bones": "Bones / 骨头",
    "blood_stains": "Blood / Blood Stains / 血液/血斑",
    "moisture_content": "Moisture Content / 水分含量",
    "damage": "Damage / 破损",
    "chicken_paw_pad": "Chicken Paw Pad / 鸡爪垫",
    "weight_per_piece": "Weight per Piece / 单重",
    "length_per_piece": "Length per Piece / 单长",
    "packaging": "Packaging / 包装",
    "inner_packing": "Inner Packing / 内包装",
    "carton_weight": "Carton Weight / 纸箱重量",
    "freezing_temp": "Freezing Temperature / 冷冻温度",
    "storage_temp": "Storage Temperature / 储藏温度",
    "transport_temp": "Transportation Temperature / 运输温度",
    "freezing_process": "Freezing Process / 冷冻工艺",
    "shelf_life": "Shelf Life / 保质期",
    "packaging_note": "Packaging Note / 包装说明",
    "product_discharge": "PRODUCT DISCHARGE / 产品卸货",
    "discharge_p1": "The shipment shall begin within 15-20 days after receipt and confirmation of the payment instrument in seller's Bank, after the contract is signed. / 发货应在合同签署后，卖方银行收到并确认付款工具后的 15-20 天内开始。",
    "discharge_p2": "The Date of bill of Lading shall be considered the date of delivery. / 提单日期应视为交货日期。",
    "discharge_p3": "Seller is responsible for all supervision, fees and/ or levies at the port of loading. / 卖方负责装货港的所有监督、费用和/或税费。",
    "discharge_p4": "Not later than 72 hours from the completion of loading, the seller's agent shall email the buyer and inform the vessel's sailing date and the expected time of arrival at the port of destination. / 卖方代理应在装货完成后的 72 小时内，通过电子邮件通知买方船舶开航日期及预计到达目的港的时间。",
    "discharge_p5": "All port of loading charges are for the account of the seller and all port of discharge charges are for the account of the buyer. / 所有装货港的费用由卖方承担，所有卸货港的费用由买方承担。",
    "commercial_terms": "COMMERCIAL TERMS / 商业条款",
    "commercial_note": "(This is our basis payment terms but still it should be editable) / (这是我们的基本付款条款，但仍然可以编辑)",
    "trial_shipment": "TRIAL SHIPMENT / 试发货",
    "trial_payment_text": "The Buyer will provide irrevocable, operative, and transferable DLC (MT700) for trial containers. The Buyer shall make 100\\% payment at the loading port against presentation of shipping documents via TT (MT 103). The Seller shall ship the goods as per the agreed Proforma Invoice and, upon completion of loading at the port of shipment, present copies of the shipping documents, including but not limited to the Bill of Lading, Commercial Invoice, Packing List, Health Certificate, and other required export documents, to the Buyer. Full payment shall be remitted by the Buyer immediately upon confirmation of loading and presentation of documents. Release of the original shipping documents shall be made only after receipt of 100\\% payment through normal banking channels via TT (MT103). / 买方将为试运集装箱提供不可撤销的、有效的、可转让的跟单信用证（DLC/MT700）。买方须在装货港凭装运单据通过电汇（TT/MT103）支付 100\\% 货款。卖方应根据约定的形式发票发货，并在装运港装货完成后，向买方提供装运单据副本，包括但不限于提单、商业发票、装箱单、健康证书及其他所需的出口单证。买方在确认装货及收到单据后，应立即汇出全款。只有通过正常银行渠道通过电汇（TT/MT103）收到 100\\% 货款后，方可放行正本装运单据。",
    "monthly_shipment": "MONTHLY SHIPMENT / 月度发货",
    "monthly_payment_text": "Buyer will open an irrevocable, operative, and transferable DLC (MT700) for the value of one month shipment quantity against the proforma invoice \\& SPA, issued and confirmed by world top 100 Banks valid for 365 + 1 days (or 180 days x 2 subject to the issuing bank's rule). Upon completion of loading and issuance of the Bill of Lading, the Seller shall provide copies of the commercial invoice, Bill of Lading, Packing List, and other relevant shipping documents to the Buyer. The Buyer shall remit 100\\% payment immediately upon confirmation of the above mentioned shipping documents. Payment shall be effected via MT103 / TT bank-to-bank SWIFT transfer. Release of the original Bill of Lading and full set of original shipping documents shall be made only after confirmation of full payment through normal banking channels. / 买方将针对形式发票和买卖协议开立不可撤销的、有效的、可转让的跟单信用证（DLC/MT700），金额为一个月发货量的价值，由全球前 100 大银行开立并保兑，有效期为 365 + 1 天（或根据开证行规定为 180 天 x 2）。装货完成并签发提单后，卖方应向买方提供商业发票、提单、装箱单及其他相关装运单据的副本。买方在确认上述装运单据后应立即支付 100\\% 的货款。付款须通过 MT103 / TT 银行间 SWIFT 转账进行。只有在通过正常银行渠道确认全额付款后，方可放行正本提单和全套正本装运单据。",
    "payment_tt": "PAYMENT VIA TELEGRAPHIC TRANSFER (TT/MT103) / 电汇支付 (TT/MT103)",
    "payment_tt_text": "The Buyer shall effect payment for shipments by way of Telegraphic Transfer (TT/MT103) upon receipt of confirmation from the Seller's nominated bank via SWIFT that the original shipping documents have been duly submitted and are held in custody by the bank. The Seller shall, prior to such confirmation, provide the Buyer with scanned/digital copies of all relevant shipping documents for advance review and verification. The Buyer will still be providing DLC MT700 as a security financial instrument for contract shipment. / 买方在通过 SWIFT 收到卖方指定银行的确认（正本装运单据已正式提交并由银行保管）后，应以电汇（TT/MT103）的方式支付货款。在确认之前，卖方应向买方提供所有相关装运单据的扫描/数字副本，以便提前审查和核实。买方仍将提供 DLC MT700 作为合同发货的担保金融工具。",
    "dlc": "DOCUMENTARY LETTER OF CREDIT (DLC/MT700) / 跟单信用证 (DLC/MT700)",
    "dlc_text": "The DLC (MT700) shall serve as a supporting financial instrument for the purpose of providing transactional assurance and security to both parties. For the avoidance of doubt, the DLC shall not constitute the primary mode of payment. Actual settlement for each shipment shall be effected exclusively via TT/MT103. / DLC (MT700) 应作为支持性的金融工具，旨在为双方提供交易保证和安全。为避免疑问，DLC 不构成主要的付款方式。每次发货的实际结算应仅通过 TT/MT103 进行。",
    "telex": "TELEX RELEASE / 电放",
    "telex_text": "The Seller shall arrange telex release of the cargo upon receipt of full payment, unless otherwise mutually agreed. / 除非双方另有约定，否则卖方在收到全款后应安排货物电放。",
    "product_doc": "PRODUCT DOCUMENTATION / 产品文件",
    "doc_intro": "A full set of the following documents which will be legitimate for shipment from Brazil will be presented. / 将提供全套在巴西合法装运的以下单据。",
    "doc_1": "Full set of clean on -- board marine bill of lading made out to order and blank endorsed, 1/3 clearly marked `Freight Prepaid'' in 1 original / 全套清洁已装船海运提单，凭指示开具并空白背书，1/3 明确标有“运费预付”字样，1份正本",
    "doc_2": "Commercial Invoice issued by the seller indicating the contract number, DLC/SBLC number, Description of the goods, gross / net weights of the goods in 1 Original. / 由卖方出具的商业发票，注明合同号、DLC/SBLC 号、货物描述、货物毛重/净重，1 份正本。",
    "doc_3": "Packaging list 1 originals showing contract no., seal no., container no., gross / net weight, B/L no., date. Quantity loaded and loading port. / 装箱单 1 份正本，显示合同号、封条号、集装箱号、毛重/净重、提单号、日期、装载数量和装货港。",
    "doc_4": "Certificate of origin issued by the relevant authority of the country of origin of Brazil in 1 original / 巴西原产国相关机构颁发的原产地证书，1 份正本",
    "doc_5": "Certificate of Quality and quantity issued by CCIC Brazil, 1 original / CCIC 巴西公司出具的质量和数量证书，1 份正本",
    "doc_6": "Veterinary health certificate issued by veterinary office for the record of China entry- Exit inspection and quarantine in 1 originals / 中国出入境检验检疫局备案兽医机构出具的兽医健康证书 1 份正本",
    "doc_7": "Insurance policy/ certificate in 1 original for 110\\% of the invoice value, covering ocean marine transportation all risk. / 保险单/凭证，1 份正本，投保金额为发票价值的 110\\%，涵盖海洋运输一切险。",
    "doc_8": "Commodity bilingual English- Chinese label samples in 1 original. / 中英文双语商品标签样本，1 份正本。",
    "doc_9": "Slaughterhouse SIF certificate in 1 copy / 屠宰场 SIF 证书 1 份副本",
    "doc_10": "Export / shipper certificate of GACC Registration in 1 Copy / 托运人海关总署注册出口证书 1 份副本",
    "doc_11": "HALAL certificate in 1 original / 清真证书 1 份正本",
    "procedures": "PROCEDURES / 程序",
    "proc_note": "(This is our basis procedure but still it should be editable) / (这是我们的基本程序，但仍应可编辑)",
    "proc_1": "The Buyer issues the LOI (Letter of Intent) to the Seller. / 买方向卖方发出意向书 (LOI)。",
    "proc_2": "The Seller issues the FCO (Full Corporate Offer) to the Buyer. / 卖方向买方发出完整企业报价 (FCO)。",
    "proc_3": "Upon acceptance, the Buyer signs, seals, and returns the FCO. / 买方接受后，签署、盖章并退回 FCO。",
    "proc_4": "The Buyer issues the ICPO (Irrevocable Corporate Purchase Order). / 买方发出不可撤销的企业采购订单 (ICPO)。",
    "proc_5": "The Seller issues the SPA (Sales and Purchase Agreement). / 卖方发出销售和采购协议 (SPA)。",
    "proc_6": "The Buyer provides POF (Proof of Funds) by BCL (Bank Comfort Letter). / 买方通过银行资金证明 (BCL) 提供资金证明 (POF)。",
    "proc_7": "Upon signing and sealing of the SPA, the Seller issues the Proforma Invoice (PI). / 签署并盖章 SPA 后，卖方发出形式发票 (PI)。",
    "proc_8": "The Buyer's bank issues an irrevocable, operative, and transferable DLC (MT700), covering the agreed shipment quantity in accordance with the SPA and payment terms. The DLC shall be issued and confirmed by a Top 100 World Bank and remain valid as per agreed contract terms. / 买方银行根据 SPA 和付款条件，就约定的发货数量开出不可撤销、有效且可转让的跟单信用证（DLC/MT700）。跟单信用证须由全球 100 强银行开出并保兑，并在约定的合同条款内保持有效。",
    "proc_9": "The Seller arranges inspection for quality and quantity through CCIC Brazil at the Seller's expense, completes loading, and prepares the shipping documents. / 卖方自费通过CCIC巴西公司安排数量和质量检验，完成装货，并准备装运单据。",
    "proc_10": "Upon completion of loading and issuance of the Bill of Lading, the Seller provides copies of shipping documents to the Buyer, including but not limited to the Bill of Lading, Commercial Invoice, Packing List, Health Certificate, and other relevant export documents. / 装货完成并出具提单后，卖方向买方提供装运单据的复印件，包括但不限于提单、商业发票、装箱单、健康证书及其他相关出口单据。",
    "proc_11": "The Buyer remits 100\\% payment immediately upon confirmation of loading and presentation of shipping documents via TT / MT103 bank-to-bank SWIFT transfer. / 买方在确认装载及收到装运单据后，须立即通过电汇/MT103 银行间 SWIFT 汇款全额（100\\%）付款。",
    "proc_12": "Release of the original Bill of Lading and full set of original shipping documents shall be made only after confirmation of 100\\% payment through normal banking channels. / 仅在通过正常银行渠道确认收到全额付款后，才会放行原提单及全套原装运单据。",
    "proc_13": "The Seller permits the Buyer or the Buyer's appointed representative to witness the loading process at the loading warehouse, at the Buyer's expense. / 卖方允许买方或买方指定代表在买方自费的情况下在装货仓库见证装货过程。",
    "proc_14": "The Buyer shall be responsible for customs clearance, unloading at destination, and any penalties arising from delayed unloading. The Buyer shall notify the Seller in writing of the appointed clearing agent details at the time of payment confirmation. / 买方负责目的地的清关、卸货以及因延迟卸货引起的任何罚金。在付款确认时，买方应书面通知卖方指定的清关代理详情。",
    "seller_details": "SELLER DETAILS / 卖方详情",
    "seller_bank": "SELLER BANKING DETAILS / 卖方银行详情",
    "contact_person": "Contact Person / 联系人",
    "whatsapp": "WhatsApp / WhatsApp",
    "bank_name": "Bank Name / 银行名称",
    "bank_address": "Bank Address / 银行地址",
    "account_name": "Account Name / 账户名称",
    "account_number": "Account Number / 账号",
    "swift_code": "Swift Code / SWIFT 代码",
    "buyer_company_info": "BUYER COMPANY INFORMATION / 买方公司信息",
    "country": "Country / 国家",
    "phone_no": "Phone No. / 电话号码",
    "buyer_bank_info": "BUYER BANK INFORMATION / 买方银行信息",
    "bank_swift_code": "Bank Swift Code / 银行 SWIFT 代码",
    "bank_officer": "Bank Officer/Email / 银行主管/邮箱",
    "bank_charges_note": "Bank Charges: All banking Charges from Buyer's Bank shall be borne by the buyer, and all banking charges incurred at Seller's Financier's Bank will be borne by the Seller Financier's. / 银行费用：买方银行的所有银行费用由买方承担，卖方融资银行产生的所有银行费用由卖方融资人承担。",
    "note_1": "Note: No contact with the Seller's or Buyer's bank(s) shall be made without the explicit written permission of the Seller or Buyer. In the event that an alternate bank account is to be used, the Seller and Buyer shall notify each other in writing of the new bank coordinates. Both parties are required to inform each other in advance before forwarding any financial instructions or correspondence to the bank. / 注：未经卖方或买方明确的书面许可，不得与卖方或买方的银行进行任何联系。如果使用备用银行账户，卖方和买方应书面通知对方新银行坐标。在将任何财务指令或信函转交给银行之前，双方必须提前相互通知。",
    "note_2": "Please Note: A final SPA will be signed between end seller and the buyer once this FCO is accepted, signed and sealed by the buyer. / 请注意：买方接受、签署并盖章本 FCO 后，最终卖方和买方之间将签署最终的 SPA。",
    "validity_offer": "VALIDITY OF OFFER / 报价有效期",
    "validity_text": "This FCO remains valid until its expiry date / 本 FCO 在其到期日之前保持有效",
    "auth_sig": "AUTHORIZED SIGNATURES / 授权签名",
    "seller_sig": "FOR AND ON BEHALF OF SELLER / 代表卖方",
    "buyer_sig": "FOR AND ON BEHALF OF BUYER / 代表买方"
};

module.exports = { labels_en, labels_zh };
